# minidisplay-lounge
substitutions:
  name: "minidisplay-lounge"
  friendly_name: "Lounge"
  room: "Lounge"

logger:

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

# Wifi Setup
wifi:
    ssid: !secret wifi_ssid
    password: !secret wifi_password

    ap:
      ssid: ${name} Fallback
      password: !secret fallback_password

captive_portal:

web_server:
  port: 80

# Packages
packages:
  setup:
    url: https://github.com/acolwill/esphome-lvgl/
    files: [minidisplay-lounge/device/device.yaml,
            minidisplay-lounge/device/sensors.yaml,
            minidisplay-lounge/device/lvgl.yaml,
            minidisplay-lounge/addon/backlight.yaml,
            minidisplay-lounge/addon/time.yaml,
            minidisplay-lounge/addon/network.yaml,
            minidisplay-lounge/assets/fonts.yaml,
            minidisplay-lounge/assets/icons.yaml,
            minidisplay-lounge/theme/button.yaml]
    refresh: 1sec
