# minidisplay-bedroom
substitutions:
  name: "minidisplay-bedroom"
  friendly_name: "Bedroom"
  room: "Bedroom"

logger:

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

# Wifi Setup
wifi:
    ssid: !secret wifi_ssid
    password: !secret wifi_password

    ap:
      ssid: ${name} Fallback
      password: !secret fallback_password

captive_portal:

web_server:
  port: 80

# Packages
packages:
  setup:
    url: https://github.com/acolwill/esphome-lvgl/
    files: [minidisplay-bedroom/device/device.yaml,
            minidisplay-bedroom/device/sensors.yaml,
            minidisplay-bedroom/device/lvgl.yaml,
            minidisplay-bedroom/addon/backlight.yaml,
            minidisplay-bedroom/addon/time.yaml,
            minidisplay-bedroom/addon/network.yaml,
            minidisplay-bedroom/assets/fonts.yaml,
            minidisplay-bedroom/assets/icons.yaml,
            minidisplay-bedroom/theme/button.yaml]
    refresh: 1sec
