# guition-esp32-s3-4848s040
substitutions:
  name: "minidisplay"
  friendly_name: "4848s040"
  room: "Home"

logger:

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

# Wifi Setup
wifi:
    ssid: !secret wifi_ssid
    password: !secret wifi_password

    ap:
      ssid: ${name} Fallback
      password: !secret fallback_password

captive_portal:

web_server:
  port: 80

# Packages
packages:
  setup:
    url: https://github.com/acolwill/esphome-lvgl/
    files: [guition-esp32-s3-4848s040/device/device.yaml,
            guition-esp32-s3-4848s040/device/sensors.yaml,
            guition-esp32-s3-4848s040/device/lvgl.yaml,
            guition-esp32-s3-4848s040/addon/backlight.yaml,
            guition-esp32-s3-4848s040/addon/time.yaml,
            guition-esp32-s3-4848s040/addon/network.yaml,
            guition-esp32-s3-4848s040/assets/fonts.yaml,
            guition-esp32-s3-4848s040/assets/icons.yaml,
            guition-esp32-s3-4848s040/theme/button.yaml]
    refresh: 1sec
